### ISSUE TITLE
Error when trying to initialise node after installing it from ComfyUI Manager

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [lks-ai/anynode#13]
I've just installed the nodes using the ComfyUI Manager and restarted, but I get this error so can't use the node:

```
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\anynode\__init__.py", line 8, in <module>
    from .nodes.any import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS, AnyNode
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\anynode\nodes\any.py", line 111, in <module>
    class AnyNode:
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\anynode\nodes\any.py", line 170, in AnyNode
    FUNCTION_REGISTRY = FunctionRegistry(schema="default", version=VERSION)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\anynode\nodes\util_functions.py", line 21, in __init__
    self.chroma_client = self.init_chromadb()
                         ^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\anynode\nodes\util_functions.py", line 27, in init_chromadb
    client = chromadb.Client(settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\chromadb\__init__.py", line 274, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\chromadb\api\client.py", line 139, in __init__
    super().__init__(settings=settings)
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\chromadb\api\client.py", line 43, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\chromadb\api\client.py", line 54, in _create_system_if_not_exists
    new_system.instance(ServerAPI)
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\chromadb\config.py", line 401, in instance
    impl = type(self)
           ^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\chromadb\api\segment.py", line 104, in __init__
    self._sysdb = self.require(SysDB)
                  ^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\chromadb\config.py", line 297, in require
    inst = self._system.instance(type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\chromadb\config.py", line 401, in instance
    impl = type(self)
           ^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\chromadb\db\impl\sqlite.py", line 89, in __init__
    os.makedirs(os.path.dirname(self._db_file), exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './F:'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\anynode module for custom nodes: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './F:'
```

**Comment by GalaxyTimeMachine** [comment]
Error seems to have cleared itself after updating, which happens every start, and restarting this morning.
